spring.application.name=AppBlopping

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/blopping
spring.datasource.username=postgres
spring.datasource.password=Gatta7
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
